#!/usr/bin/env python3
"""Generate the competitor-claim comparison data from the database."""
import os, sys, json
sys.path.insert(0, os.path.dirname(__file__))
from db import query

rows = query("""SELECT c.subject, c.domain, c.url, c.claim, c.value_text, c.basis,
                       c.population, COALESCE(c.cited_source,''), q.keyword
                FROM competitor_claim c LEFT JOIN serp_query q ON q.id = c.query_id
                ORDER BY c.subject, c.basis, c.domain;""")
serp = query("""SELECT q.keyword, r.rank_absolute, r.result_type, r.domain,
                       r.title, r.cited_by_ai
                FROM serp_result r JOIN serp_query q ON q.id = r.query_id
                ORDER BY q.keyword, r.rank_absolute;""")

def pad(r, n): return list(r) + [""] * (n - len(r))
def js(o): return json.dumps(o, separators=(",", ":"))

claims = []
for r in rows:
    subj, dom, url, claim, val, basis, pop, src, kw = pad(r, 9)
    claims.append(dict(subject=subj, domain=dom, url=url, claim=claim, value=val,
                       basis=basis, population=pop, citedSource=src, keyword=kw))
results = []
for r in serp:
    kw, rank, typ, dom, title, ai = pad(r, 6)
    results.append(dict(keyword=kw, rank=int(rank), type=typ, domain=dom,
                        title=title, citedByAi=ai == "t"))

out = ['/**',
       ' * What the pages currently ranking for these questions actually claim,',
       ' * and what each of them measured.',
       ' *',
       ' * Generated by data/corpus/gen_claims_ts.py. Captured from live SERPs,',
       ' * stored in research_corpus, never hand-typed.',
       ' *',
       ' * The basis field is the whole point. "Snapchat is 38% 18-24" and',
       ' * "Snapchat is 90% 13-24" are not competing estimates of one number:',
       ' * one counts ad-platform reach globally, the other counts it in',
       ' * selected markets, and neither counts people. Published side by side',
       ' * with what they measured, the disagreement explains itself.',
       ' */',
       '',
       'export type ClaimBasis = "ad_audience" | "survey" | "vendor_panel" | "unstated";',
       '',
       'export const BASIS_META: Record<ClaimBasis, { label: string; what: string; color: string }> = {',
       '  survey: {',
       '    label: "Probability sample",',
       '    what: "A random sample of people, with a published sample size and margin of error. The only basis that supports a claim about a population.",',
       '    color: "#10b981",',
       '  },',
       '  vendor_panel: {',
       '    label: "Opt-in panel",',
       '    what: "People who signed up to be surveyed. Useful, but panel members are not a random sample of the country and the tool rarely says how many answered.",',
       '    color: "#3b82f6",',
       '  },',
       '  ad_audience: {',
       '    label: "Ad-platform reach",',
       '    what: "The number the advertising tool shows when you build an audience. It counts reachable accounts, not people: one person with two accounts counts twice, and a bot counts once.",',
       '    color: "#f59e0b",',
       '  },',
       '  unstated: {',
       '    label: "No basis given",',
       '    what: "A percentage with no sample, no method and no source you can open. Most commonly a figure copied from another page that copied it.",',
       '    color: "#ef4444",',
       '  },',
       '};',
       '',
       'export interface CompetitorClaim {',
       '  subject: string;',
       '  domain: string;',
       '  url: string;',
       '  claim: string;',
       '  value: string;',
       '  basis: ClaimBasis;',
       '  population: string;',
       '  citedSource: string;',
       '  keyword: string;',
       '}',
       '',
       'export const COMPETITOR_CLAIMS: CompetitorClaim[] = [']
for c in claims:
    out.append("  " + js(c).replace('":', '": ').replace(',"', ', "') + ",")
out += ['];', '',
        'export interface SerpRow { keyword: string; rank: number; type: string; domain: string; title: string; citedByAi: boolean; }',
        '',
        'export const SERP_ROWS: SerpRow[] = [']
for r in results:
    out.append("  " + js(r).replace('":', '": ').replace(',"', ', "') + ",")
out += ['];', '',
        'export const claimsFor = (subject: string) =>',
        '  COMPETITOR_CLAIMS.filter((c) => c.subject === subject);', '']
dest = os.path.join(os.path.dirname(__file__), "..", "..", "src", "data", "competitorClaims.ts")
open(dest, "w").write("\n".join(out))
print(f"{len(claims)} claims, {len(results)} serp rows")
