#!/usr/bin/env python3
"""
Generate the state-level context layer from the mined USAFacts answers.

This is the layer the tool could not reach before: it could only ever say "US
adults". Now a persona can carry a place, and the national baseline underneath
it changes.

Deliberately kept as CONTEXT, not reach. Pew publishes no state-level platform
cuts, so nothing here is combined with a platform figure. Doing that would mean
inventing a state-level reach number, which is the exact move this corpus
exists to refuse.
"""
import os, sys, json, re
sys.path.insert(0, os.path.dirname(__file__))
from db import query

def pad(r, n): return list(r) + [""] * (n - len(r))
def js(o): return json.dumps(o, separators=(",", ":"))

rows = query("""SELECT o.geo, m.slug, m.label, m.topic, o.value, o.answer_text, o.period
                FROM observation o JOIN metric m ON m.id = o.metric_id
                WHERE o.geo_kind = 'state' ORDER BY o.geo, m.topic, m.slug;""")

places, metrics = {}, {}
for r in rows:
    geo, mslug, label, topic, val, ans, per = pad(r, 7)
    if geo in ("united-states",):
        continue
    name = geo.replace("-", " ").title().replace(" Of ", " of ")
    p = places.setdefault(geo, {"slug": geo, "name": name, "facts": []})
    p["facts"].append({"metric": mslug, "value": float(val), "answer": (ans or "")[:300], "period": per})
    metrics[mslug] = {"slug": mslug, "label": label, "topic": topic}

out = ["/**",
       " * State-level context, mined from USAFacts answer pages.",
       " *",
       " * Generated by data/corpus/gen_places_ts.py. Each fact keeps the sentence",
       " * it came from, so a reader can see the claim rather than a bare number.",
       " *",
       " * This is CONTEXT and never reach. Pew publishes no state-level platform",
       " * breakdowns, so nothing here is combined with a platform figure: a",
       " * state-level reach number would have to be invented, and inventing it is",
       " * the one thing this corpus will not do.",
       " */",
       "",
       "export interface PlaceFact { metric: string; value: number; answer: string; period: string; }",
       "export interface Place { slug: string; name: string; facts: PlaceFact[]; }",
       "export interface PlaceMetric { slug: string; label: string; topic: string; }",
       "",
       "export const PLACE_METRICS: PlaceMetric[] = ["]
for m in sorted(metrics.values(), key=lambda x: (x["topic"], x["slug"])):
    out.append("  " + js(m) + ",")
out += ["];", "", "export const PLACES: Place[] = ["]
for p in sorted(places.values(), key=lambda x: x["name"]):
    out.append("  " + js(p) + ",")
out += ["];", "",
        "export const placeBySlug = (s: string) => PLACES.find((p) => p.slug === s);",
        "export const placeMetric = (s: string) => PLACE_METRICS.find((m) => m.slug === s);", ""]
dest = os.path.join(os.path.dirname(__file__), "..", "..", "src", "data", "places.ts")
open(dest, "w").write("\n".join(out))
print(f"{len(places)} places, {len(metrics)} metrics, {len(rows)} facts")
