#!/usr/bin/env python3
"""Generate the competitor page and source-chain data."""
import os, sys, json
sys.path.insert(0, os.path.dirname(__file__))
from db import query

def pad(r, n): return list(r) + [""] * (n - len(r))
def js(o): return json.dumps(o, separators=(",", ":"))

pages = query("""SELECT subject, domain, url, title, claim_count,
                        COALESCE(latest_year,''), COALESCE(latest_period,'')
                 FROM competitor_page ORDER BY subject;""")
srcs = query("""SELECT cp.subject, cs.domain, cs.url, cs.kind
                FROM competitor_source cs JOIN competitor_page cp ON cp.id = cs.page_id
                ORDER BY cp.subject, cs.kind, cs.domain;""")
shared = query("""SELECT cs.domain, count(DISTINCT cp.subject)
                  FROM competitor_source cs JOIN competitor_page cp ON cp.id = cs.page_id
                  GROUP BY 1 HAVING count(DISTINCT cp.subject) >= 3 ORDER BY 2 DESC;""")

by = {}
for r in pages:
    subj, dom, url, title, n, yr, per = pad(r, 7)
    by[subj] = dict(subject=subj, domain=dom, url=url, title=title,
                    claimCount=int(n), latestYear=yr, latestPeriod=per, sources=[])
for r in srcs:
    subj, dom, url, kind = pad(r, 4)
    if subj in by:
        by[subj]["sources"].append(dict(domain=dom, url=url, kind=kind))

out = ['/**',
       ' * Who currently owns each platform query, and where their numbers come from.',
       ' *',
       ' * Generated by data/corpus/gen_competitors_ts.py from research_corpus.',
       ' *',
       ' * The pattern is the point. Across nine platform pages there are 94',
       ' * outbound source links to 58 domains, and two of those domains appear',
       ' * on all nine: DataReportal and Statista. Both are aggregators, and',
       ' * DataReportal states plainly what its figures are: the platform',
       ' * advertising tools can reach approximately X. So the whole set traces',
       ' * back to ad dashboards. One link in 94 goes to a probability sample.',
       ' */',
       '',
       'export interface CompetitorSource { domain: string; url: string; kind: string; }',
       'export interface CompetitorPage {',
       '  subject: string;',
       '  domain: string;',
       '  url: string;',
       '  title: string;',
       '  claimCount: number;',
       '  /** The most recent period the page itself references. */',
       '  latestYear: string;',
       '  latestPeriod: string;',
       '  sources: CompetitorSource[];',
       '}',
       '',
       'export const COMPETITOR_PAGES: CompetitorPage[] = [']
for subj in sorted(by):
    out.append("  " + js(by[subj]) + ",")
out += ['];', '',
        '/** Domains cited across three or more platform pages: the real upstream. */',
        'export const SHARED_SOURCES: { domain: string; platforms: number }[] = [']
for r in shared:
    dom, n = pad(r, 2)
    out.append(f'  {{ domain: {js(dom)}, platforms: {int(n)} }},')
out += ['];', '',
        'export const competitorFor = (subject: string) =>',
        '  COMPETITOR_PAGES.find((p) => p.subject === subject);', '']
dest = os.path.join(os.path.dirname(__file__), "..", "..", "src", "data", "competitorPages.ts")
open(dest, "w").write("\n".join(out))
print(f"{len(by)} pages, {len(srcs)} source links, {len(shared)} shared sources")
