#!/usr/bin/env python3
"""gen-transcript.py: the brightonSEO San Diego 2026 talk transcript, from its caption file.

Usage: python3 scripts/brightonseo-support/gen-transcript.py [edition_dir]
       (default edition_dir: ~/Downloads/Final_Edition)

Source: Full_Talk_15m.srt, the captions of the 15-minute edit. That edit is the
video on LinkedIn (its player reports 900.01 s), so the timestamps line up.
Captions were generated locally and edited for readability; unclear speech is
marked [inaudible] and kept that way rather than guessed.

Writes:
  - src/data/brightonTranscript.ts: paragraphs under the edit's own chapters
    (Full_Talk_Chapters.txt), each with its start time and speaker.
  - public/talks/brightonseo-san-diego-2026/transcript.vtt: the caption file.
"""
import json, re, shutil, sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ED = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "Downloads/Final_Edition"
HOST_UNTIL = 14.0  # the session host introduces the talk until the applause at 0:14
PARA_WORDS = 70    # start a new paragraph at the first sentence end past this many words


def secs(ts):
    h, m, rest = ts.replace(",", ".").split(":")
    return int(h) * 3600 + int(m) * 60 + float(rest)


srt = (ED / "Full_Talk_15m.srt").read_text(encoding="utf-8-sig")
cues = [(secs(a), " ".join(t.split()))
        for a, _, t in re.findall(r"\d+\s*\n(\d\d:\d\d:\d\d[,.]\d{3}) --> (\d\d:\d\d:\d\d[,.]\d{3})\s*\n(.*?)(?:\n\s*\n|\Z)", srt, re.S)]
chapters = []
for line in (ED / "Full_Talk_Chapters.txt").read_text().splitlines():
    m = re.match(r"(\d+):(\d\d)\s+(.+)", line.strip())
    if m:
        chapters.append({"at": int(m.group(1)) * 60 + int(m.group(2)), "title": m.group(3).strip(), "paragraphs": []})
assert chapters and chapters[0]["at"] == 0, "chapter file must start at 0:00"

for c in chapters:
    c["_cues"] = []
for at, text in cues:
    ch = [c for c in chapters if c["at"] <= at + 0.5][-1]
    ch["_cues"].append((at, text))

for c in chapters:
    para, words, speaker = None, 0, None
    for at, text in c.pop("_cues"):
        who = "host" if at < HOST_UNTIL and text != "[Applause]" else "venkata"
        if para is None or who != speaker or (words >= PARA_WORDS and re.search(r"[.!?\]]$", para["text"])):
            para = {"at": round(at), "speaker": who, "text": text}
            c["paragraphs"].append(para)
            words, speaker = len(text.split()), who
        else:
            para["text"] += " " + text
            words += len(text.split())

full = " ".join(p["text"] for c in chapters for p in c["paragraphs"])
meta = {
    "source": "Captions of the 15-minute edit, generated locally and edited for readability",
    "duration": 900,
    "words": len(full.split()),
    "inaudible": full.count("[inaudible]"),
    "vtt": "/talks/brightonseo-san-diego-2026/transcript.vtt",
}
out = REPO / "public/talks/brightonseo-san-diego-2026"
out.mkdir(parents=True, exist_ok=True)
shutil.copyfile(ED / "Full_Talk_15m.vtt", out / "transcript.vtt")

TS = lambda v: json.dumps(v, ensure_ascii=False, indent=2)
(REPO / "src/data/brightonTranscript.ts").write_text(f'''/**
 * brightonTranscript.ts: the transcript of "Industrial Level Classification
 * with Intent", brightonSEO San Diego 2026, as the 15-minute edit plays it.
 *
 * GENERATED by scripts/brightonseo-support/gen-transcript.py from the edit's
 * caption file. Do not edit by hand: fix the SRT and rerun. The edit is the
 * video posted on LinkedIn, so every timestamp here matches that player.
 * Unclear speech stays marked [inaudible] rather than guessed.
 */

export interface TranscriptParagraph {{
  /** Seconds from the start of the 15-minute edit. */
  at: number;
  speaker: "host" | "venkata";
  text: string;
}}

export interface TranscriptChapter {{
  at: number;
  title: string;
  paragraphs: TranscriptParagraph[];
}}

export const TRANSCRIPT_META = {TS(meta)} as const;

export const TRANSCRIPT: TranscriptChapter[] = {TS(chapters)};
''')
print(json.dumps(meta), "| chapters", len(chapters), "| paragraphs", sum(len(c["paragraphs"]) for c in chapters))
