#!/usr/bin/env python3
"""
gen-paper-covers.py: render each paper's real first page to a web image.

A bibliography row is a claim; the page itself is the evidence. These are
screenshots of page 1 of the actual PDF, so a reader sees the journal header,
the byline with Venkata's position in it, and the abstract without leaving the
site. Nothing is composed, redrawn or mocked up: if the PDF cannot be opened,
the paper simply gets no image.

Two deliberate choices:

  WHOLE PAGE, NO CROP. A crop of a page is a derivative of it; a faithful
  scaled copy is not. The Springer article is CC BY-NC-ND, which permits
  verbatim reproduction with attribution and forbids adapted material, so the
  page is reproduced whole and credited in the caption.

  620px WIDE. The card renders around 260 CSS px, so 620 is past 2x and stays
  crisp on a retina screen. It is also small enough that 8pt body type, which
  on the JDSMM page includes the authors' printed phone and email, does not
  survive as machine-readable text. The point of the image is that you can see
  it is a real paper, not that you can read it here.

Usage:  python3 scripts/gen-paper-covers.py
Needs:  pip install pymupdf

Sources are local PDFs, listed in SOURCES below. The Springer PDF is the
publisher's open-access copy; re-fetch it from the DOI if it is missing.
"""
from __future__ import annotations

import pathlib
import sys

try:
    import fitz  # PyMuPDF
except ImportError:
    sys.exit("pymupdf is required: pip install pymupdf")

HOME = pathlib.Path.home()
REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / "public" / "research" / "papers"

WIDTH_PX = 620
JPEG_QUALITY = 84

# slug -> (source PDF, a phrase that must appear on page 1)
# The phrase is the guard: it proves the file on disk is the paper the slug
# claims, so a renamed or replaced download cannot quietly ship as the wrong
# cover.
SOURCES: dict[str, tuple[pathlib.Path, str]] = {
    "llms-disrupting-search": (
        HOME / "Downloads" / "ssrn-6512878.pdf",
        "The Disruption of Search Engine Optimization",
    ),
    "reward-hacking-agentic-llms": (
        pathlib.Path("/tmp/springer-reward-hacking.pdf"),
        "A survey of reward hacking in agentic large",
    ),
    "ai-helpful-content-ecommerce": (
        HOME / "Downloads" / "JDSMM_12_3_JDSMM0001_Macumber.pdf",
        "How artificial intelligence can be",
    ),
}


def flatten(text: str) -> str:
    return " ".join(text.split())


MANIFEST = REPO / "src" / "data" / "paperCovers.ts"

MANIFEST_HEAD = '''/**
 * Generated by scripts/gen-paper-covers.py. Do not edit by hand.
 *
 * Width and height come from the rendered file itself, so the browser can
 * reserve the exact box before the image arrives and the paper rows do not
 * jump as they load. Page sizes differ between publishers (A4 and US Letter),
 * which is why these are measured per paper rather than assumed.
 */
export interface PaperCover {
  src: string;
  width: number;
  height: number;
}

export const PAPER_COVERS: Record<string, PaperCover> = {
'''


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    failures = 0
    manifest: dict[str, tuple[int, int]] = {}

    for slug, (src, expect) in SOURCES.items():
        if not src.exists():
            print(f"MISS  {slug}: no PDF at {src}")
            failures += 1
            continue

        doc = fitz.open(src)
        page = doc[0]
        body = flatten(page.get_text())
        if flatten(expect).lower() not in body.lower():
            print(f"WRONG {slug}: {src.name} page 1 does not contain {expect!r}")
            failures += 1
            continue

        zoom = WIDTH_PX / page.rect.width
        pix = page.get_pixmap(matrix=fitz.Matrix(zoom, zoom), alpha=False)
        dst = OUT / f"{slug}.jpg"
        pix.save(dst, jpg_quality=JPEG_QUALITY)
        manifest[slug] = (pix.width, pix.height)
        print(f"ok    {slug}: {pix.width}x{pix.height}, {dst.stat().st_size // 1024} KB  <- {src.name}")

    if manifest:
        rows = "".join(
            f'  "{slug}": {{ src: "/research/papers/{slug}.jpg", width: {w}, height: {h} }},\n'
            for slug, (w, h) in manifest.items()
        )
        MANIFEST.write_text(MANIFEST_HEAD + rows + "};\n")
        print(f"\nwrote {MANIFEST.relative_to(REPO)} ({len(manifest)} covers)")

    if failures:
        print(f"{failures} cover(s) not written.")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
