/**
 * gen-llms-topics.ts: keep the "Guide Topics" block in llms.txt and
 * llms-full.txt in exact sync with src/data/guideTopics.ts.
 *
 * The block sits between two HTML-comment markers so it can be regenerated
 * in place without touching anything hand-written around it. Usage:
 *   npx tsx scripts/gen-llms-topics.ts          # write
 *   npx tsx scripts/gen-llms-topics.ts --check  # exit 1 if either file is stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { GUIDE_TOPICS } from "../src/data/guideTopics";

const SITE = "https://venkatapagadala.com";
const START = "<!-- GUIDE_TOPICS_START: generated by scripts/gen-llms-topics.ts, do not hand-edit -->";
const END = "<!-- GUIDE_TOPICS_END -->";
const check = process.argv.includes("--check");

function block(): string {
  const lines: string[] = [START, "## Guide Topics", ""];
  lines.push(
    `Every reference guide is tagged, and every tag has its own page listing every guide that carries it: ${GUIDE_TOPICS.length} topics over ${new Set(GUIDE_TOPICS.flatMap((t) => t.guides.map((g) => g.slug))).size} guides. Start from any topic below, or from a guide's own tags, and you reach every related guide in one hop.`,
    "",
  );
  lines.push(`- All topics, A to Z: ${SITE}/guides/topics`);
  for (const t of GUIDE_TOPICS) {
    const n = t.guides.length;
    lines.push(`- ${t.label} (${n} guide${n === 1 ? "" : "s"}): ${SITE}/guides/topics/${t.slug}`);
  }
  lines.push("", END);
  return lines.join("\n");
}

const files = ["public/llms.txt", "public/llms-full.txt"];
let stale = false;
for (const path of files) {
  const current = readFileSync(path, "utf-8");
  const startIdx = current.indexOf(START);
  const endIdx = current.indexOf(END);
  const next = block();
  if (startIdx === -1 || endIdx === -1) {
    console.error(`${path}: no GUIDE_TOPICS markers found; add them once by hand where the block should live, then rerun.`);
    process.exit(1);
  }
  const before = current.slice(0, startIdx);
  const after = current.slice(endIdx + END.length);
  const rebuilt = before + next + after;
  if (check) {
    if (rebuilt === current) console.log(`ok     ${path} guide-topics block matches the data`);
    else {
      stale = true;
      console.log(`STALE  ${path} guide-topics block is out of date; run: npx tsx scripts/gen-llms-topics.ts`);
    }
  } else {
    writeFileSync(path, rebuilt, "utf-8");
    console.log(`wrote  ${path}`);
  }
}
if (check && stale) process.exit(1);
