/**
 * brightonPhotos.ts: the photos on the brightonSEO San Diego 2026 recap page.
 *
 * GENERATED by scripts/brightonseo-support/export_photos.py. Do not edit by
 * hand: change the list in the script and rerun. src is the large file (long
 * edge 1600), srcSm the grid size (long edge 800); both are WebP with
 * every bit of metadata stripped, GPS included.
 */

export interface TalkPhoto {
  src: string;
  width: number;
  height: number;
  srcSm: string;
  widthSm: number;
  heightSm: number;
  alt: string;
  caption: string;
}

export const PHOTOS: TalkPhoto[] = [
  {
    "src": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-stage-pointing-to-audience.webp?v=a2552668",
    "width": 1600,
    "height": 1200,
    "srcSm": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-stage-pointing-to-audience-sm.webp?v=16929339",
    "widthSm": 800,
    "heightSm": 600,
    "alt": "Venkata Pagadala on the Track 1 stage at brightonSEO San Diego 2026, pointing to the audience, with the agenda slide on the screen beside him",
    "caption": "Pointing to the room with the agenda slide up."
  },
  {
    "src": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-track-1-stage.webp?v=6d9949ed",
    "width": 1200,
    "height": 1600,
    "srcSm": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-track-1-stage-sm.webp?v=7e447cf4",
    "widthSm": 600,
    "heightSm": 800,
    "alt": "Venkata Pagadala speaking on stage beside the Track 1 lectern at brightonSEO San Diego 2026",
    "caption": "On stage in Track 1."
  },
  {
    "src": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-view-from-audience.webp?v=8e426cd1",
    "width": 1600,
    "height": 1200,
    "srcSm": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-view-from-audience-sm.webp?v=dcafacff",
    "widthSm": 800,
    "heightSm": 600,
    "alt": "View from the audience: Venkata Pagadala at the Track 1 lectern, the agenda slide on the big screen, and attendees photographing it with their phones",
    "caption": "From the seats, while the agenda slide was up."
  },
  {
    "src": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-speaking-clicker-in-hand.webp?v=4ce09433",
    "width": 1200,
    "height": 1600,
    "srcSm": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-speaking-clicker-in-hand-sm.webp?v=f2fbb2d0",
    "widthSm": 600,
    "heightSm": 800,
    "alt": "Venkata Pagadala mid-talk at brightonSEO San Diego 2026, clicker in hand, in front of the sponsor wall",
    "caption": "Mid-talk, clicker in hand."
  },
  {
    "src": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-agenda-slide.webp?v=6003c2b1",
    "width": 1600,
    "height": 1200,
    "srcSm": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-agenda-slide-sm.webp?v=5e7eac29",
    "widthSm": 800,
    "heightSm": 600,
    "alt": "Venkata Pagadala on stage at brightonSEO San Diego 2026 beside the agenda slide: the thesis, two cases, a new dad gets a new car, four engines and one pattern, the method, and building the system",
    "caption": "The agenda: six parts, from the thesis to building the system."
  },
  {
    "src": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-speaking-close-up.webp?v=8ea5d975",
    "width": 1200,
    "height": 1600,
    "srcSm": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-speaking-close-up-sm.webp?v=dce4f8e7",
    "widthSm": 600,
    "heightSm": 800,
    "alt": "Close view of Venkata Pagadala speaking at brightonSEO San Diego 2026, wearing his speaker badge",
    "caption": "A closer view, mid-talk."
  },
  {
    "src": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-title-slide-track-1.webp?v=24b4bca7",
    "width": 1600,
    "height": 1200,
    "srcSm": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-title-slide-track-1-sm.webp?v=cb213d77",
    "widthSm": 800,
    "heightSm": 600,
    "alt": "The Track 1 room at brightonSEO San Diego 2026 before the talk, with the title slide, User First, Algorithm Second, on the screen",
    "caption": "The title slide, up in Track 1 before the talk."
  },
  {
    "src": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-expo-hall-selfie.webp?v=ffdd1a0a",
    "width": 1200,
    "height": 1600,
    "srcSm": "/talks/brightonseo-san-diego-2026/photos/venkata-pagadala-brightonseo-san-diego-2026-expo-hall-selfie-sm.webp?v=c80774e2",
    "widthSm": 600,
    "heightSm": 800,
    "alt": "Selfie of Venkata Pagadala, wearing his brightonSEO San Diego speaker badge, with a fellow attendee in the expo hall",
    "caption": "Between sessions in the expo hall."
  }
];
