/**
 * brightonTranscript.ts: the transcript of "Industrial Level Classification
 * with Intent", brightonSEO San Diego 2026, as the 15-minute edit plays it.
 *
 * GENERATED by scripts/brightonseo-support/gen-transcript.py from the edit's
 * caption file. Do not edit by hand: fix the SRT and rerun. The edit is the
 * video posted on LinkedIn, so every timestamp here matches that player.
 * Unclear speech stays marked [inaudible] rather than guessed.
 */

export interface TranscriptParagraph {
  /** Seconds from the start of the 15-minute edit. */
  at: number;
  speaker: "host" | "venkata";
  text: string;
}

export interface TranscriptChapter {
  at: number;
  title: string;
  paragraphs: TranscriptParagraph[];
}

export const TRANSCRIPT_META = {
  "source": "Captions of the 15-minute edit, generated locally and edited for readability",
  "duration": 900,
  "words": 2096,
  "inaudible": 20,
  "vtt": "/talks/brightonseo-san-diego-2026/transcript.vtt"
} as const;

export const TRANSCRIPT: TranscriptChapter[] = [
  {
    "at": 0,
    "title": "Introduction",
    "paragraphs": [
      {
        "at": 0,
        "speaker": "host",
        "text": "And he is going to be speaking about users, pain points, and intent. And he does AI search and SEO at AT&T. So I'm excited to hear what they're up to."
      },
      {
        "at": 14,
        "speaker": "venkata",
        "text": "[Applause] Thank you. Thank you, everyone. I will make sure this 20 minutes is valid. So, these are the things I'm going to talk today. I'm going to talk about volume and talk about users, pain points, and intent. Why it's ten times more important than blindly following volume. And of course, because my co-speakers did a great job explaining that, I'm going to share a little bit more on that."
      },
      {
        "at": 52,
        "speaker": "venkata",
        "text": "So user first, algorithm second. Again, I don't want to chase algorithms because no one really knows how [inaudible] No one knows how it works. [inaudible] OpenAI, Claude, whatever, and they launch every [inaudible] So the retrieval method is different. So do I want to chase algorithms or models or [inaudible], or, for example, [inaudible], so do I want to care about that? Or do I want to care about users?"
      },
      {
        "at": 93,
        "speaker": "venkata",
        "text": "So simple, I think I'm going to talk about the thesis, two case studies I implemented with a great team, and these are real case studies, and third about how I bought a new car, and what was my journey from point A to purchasing. And let's talk about AI and the method. And the key important thing here is building something for myself is easy. When you're working for an enterprise, you need to build a system at scale that can be used by multiple users."
      },
      {
        "at": 132,
        "speaker": "venkata",
        "text": "Thank you. [inaudible]"
      }
    ]
  },
  {
    "at": 135,
    "title": "Zero volume, real demand",
    "paragraphs": [
      {
        "at": 135,
        "speaker": "venkata",
        "text": "So, zero volume is not a zero demand. So, trust ahead of sales. So, this is a case study. This is an industry leader site, and we want to run an experiment on using, we ignored search volume. We found that users want information that is evergreen, that's going to stay long. So example, let's take an example of area codes. People search for which number is coming from this location."
      },
      {
        "at": 167,
        "speaker": "venkata",
        "text": "That doesn't have any commercial value. And we know that for a fact. But we want to be, we want to build a content that is relevant for industry at scale using programmatic SEO strategies, that is going to be staying forever and earn trust. And we did an experiment exactly [inaudible] years ago. And again, I can't use the first-party data sources to show, but this is an estimate of the impact."
      },
      {
        "at": 195,
        "speaker": "venkata",
        "text": "We almost drove about half a million impressions, clicks, I don't really care about that. But the key thing is, people genuinely love the source, and we didn't follow the SEO strategy or AI strategy. Every AI platform, every search platform are citing our sources. We never tried to do that, but it happened. That's the impact when you focus on users and create a meaningful content and the AI citations, search rankings will follow those."
      }
    ]
  },
  {
    "at": 228,
    "title": "Case study: useful content",
    "paragraphs": [
      {
        "at": 228,
        "speaker": "venkata",
        "text": "Let's talk about case study two and when I joined the company, they have a decent amount of pages. We analyzed the user behavior and the bounce rate was significantly bad. So, rather than searching volumes, keyword data, all these things, I decided to think like a user. Okay, so I'm reading this content, I hate this content. Why? I don't want to read 3,000 words of a guide. Okay, in my feedback, I asked a couple of my team members and did a small test."
      },
      {
        "at": 266,
        "speaker": "venkata",
        "text": "And everyone said the exact same thing. Who wants to read 3,000 words of a guide? They want the videos. So we created the videos and injected into these pages. You can see the video snippets went up to 18,000. Again, that's for the metrics. I am happy. The metric I am happy about is users are happy because we are producing what they need."
      }
    ]
  },
  {
    "at": 291,
    "title": "The car-buying journey",
    "paragraphs": [
      {
        "at": 291,
        "speaker": "venkata",
        "text": "So, I'm a new dad, so I was trying to upgrade my car, [inaudible] and then also my family and safety. I decided to buy a Toyota Grand Highlander Hybrid. I was reading pages, web pages, and I hated it. Everyone is like, oh, this is the best, this is the best, this is the best. No, I don't want to buy a $60,000 product based on sales page. I genuinely want the users who bought the product and share their reviews."
      },
      {
        "at": 327,
        "speaker": "venkata",
        "text": "Then I landed on a Facebook group dedicated to people who bought Grand Highlanders. And they're sharing the perspective of which model to buy, why they like specific things, which dealership is best to buy from. And these are the queries we need to answer to our users. It's not about search volume, it's not about anything else. you need to find the real queries that people are actually typing in different platforms based on their persona or whatever it may be and try to answer them."
      },
      {
        "at": 356,
        "speaker": "venkata",
        "text": "If you can answer this query, many people lost my purchase because they were not answering the specific questions. So, again, if I use traditional tools, I'm not saying traditional tools are bad, but they're only good for direction. The volume is not a strategy. You understand the users and trying to build a content around that. And content doesn't mean that textual content. It can be video, audio, podcast, newsletters, whatever it may be."
      },
      {
        "at": 385,
        "speaker": "venkata",
        "text": "That's where real success happens."
      }
    ]
  },
  {
    "at": 389,
    "title": "Queries become conversations",
    "paragraphs": [
      {
        "at": 389,
        "speaker": "venkata",
        "text": "Again, I mainly, I don't have all the answers which I'm asking here, because keywords tracking was great. And Google used to be not personalizing results. And also, very short, one or two keywords. But no one is trying to search, like, Grand Highlander. People are searching, like, I want SUV with highest mileage and most relevant brand. So keywords are transforming into conversations."
      }
    ]
  },
  {
    "at": 421,
    "title": "AI retrieval",
    "paragraphs": [
      {
        "at": 421,
        "speaker": "venkata",
        "text": "So I was trying to search this query in different platforms to understand the reviewers. [inaudible] is trying to pull the data from Facebook, Facebook groups, and then [inaudible] is trying to pull from Reddit. And Gemini, similar. Google [inaudible] from multiple sources. So here I'm not talking about how Reddit is citing my [inaudible] Who cares if you have a meaningful content? It's not about Reddit. It's not about YouTube."
      },
      {
        "at": 458,
        "speaker": "venkata",
        "text": "It's a moving target. You need to find where your users are spending the most time."
      }
    ]
  },
  {
    "at": 464,
    "title": "The method",
    "paragraphs": [
      {
        "at": 464,
        "speaker": "venkata",
        "text": "So the method, I'm going to share the method. Here is how I do it. So these four slides will be the most important slides in this entire presentation. So we heavily focus on search data, but Google My Business reviews."
      }
    ]
  },
  {
    "at": 480,
    "title": "Reviews and pain points",
    "paragraphs": [
      {
        "at": 480,
        "speaker": "venkata",
        "text": "There is a roofing company in New York and how I use the reviews to understand the pain points. If you analyze all the roofers in New York, analyze, classify the reviews and response rates and variance, then you will understand the pain point of the roofers. It can be expensive pricing, they are doing a bad job, or they don't serve [inaudible]. So if you can solve the pain point via content and SEO strategies, That's where the commercial traffic follows."
      }
    ]
  },
  {
    "at": 512,
    "title": "Video and social platforms",
    "paragraphs": [
      {
        "at": 512,
        "speaker": "venkata",
        "text": "Again, the biggest search engine of Google is probably YouTube. People talk, comment, respond, engage in YouTube, in YouTube platform. But are we pulling the content, classifying it to understand users, how they're behaving in YouTube. Again, Twitter competitors, Reddit. People know that TikTok specific age group of audience who love to spend more on TikTok. So they like short-form content. They want instant answers. Example, are we serving the product if the product is going to target them?"
      },
      {
        "at": 551,
        "speaker": "venkata",
        "text": "Which is, we keep it as a classic example to understand what are the topics we need to cover."
      }
    ]
  },
  {
    "at": 557,
    "title": "Conference insights",
    "paragraphs": [
      {
        "at": 557,
        "speaker": "venkata",
        "text": "So, conference insights. I went to multiple conferences to understand missing topics. topics I don't know like this. I learned a lot from different speakers. So similarly, if you go to industry relevant conferences like [inaudible] or telecom or something like that, you'll know a lot from that. So this is pretty much public data influence in the podcast."
      }
    ]
  },
  {
    "at": 583,
    "title": "Earnings calls and jobs",
    "paragraphs": [
      {
        "at": 583,
        "speaker": "venkata",
        "text": "The key thing is the earnings calls. I collect the data from earnings calls. Why? Am I mad? No. I know what's coming about my competitors. My competitor says, \"We allocated this much on budget on X, Y, Z product.\" Then I know for a fact they're going to take our market share. Do I need to react or do I need to react after they took my market share?"
      },
      {
        "at": 610,
        "speaker": "venkata",
        "text": "Or I create a patch and I tag them ahead. So that's where earnings calls come in. Job postings. If your competitor is hiring for example, like AEO, SEO, GEO, whatever it may be. Then, you know for a fact, they're investing money to take market share in AI space. So that's why you need to keep an eye on the job postings."
      }
    ]
  },
  {
    "at": 633,
    "title": "Research and regulations",
    "paragraphs": [
      {
        "at": 633,
        "speaker": "venkata",
        "text": "Similarly, research papers and regulations. Research paper, why? People write research papers. They use a lot of data, certified data, actual data, in order to write papers. example. I built a tool, the open source tool. No email required, no subscription, no follow required. I'll make sure that anyone can access it. So, I used these datasets to build a personal tool."
      }
    ]
  },
  {
    "at": 660,
    "title": "Classify by persona",
    "paragraphs": [
      {
        "at": 660,
        "speaker": "venkata",
        "text": "And there can be one product, different personas, different queries for the region. I analyzed 5.6 million queries, no one really cares if I say that, but if I classify that map with personas and build a product, then the returns would be, the returns in the graph speaks about that. And classification is the core thing. But I made myself classify the data because I know my industry better than [inaudible]."
      }
    ]
  },
  {
    "at": 693,
    "title": "Map the industry",
    "paragraphs": [
      {
        "at": 693,
        "speaker": "venkata",
        "text": "So, rather than topics, keywords, clusters, I try to [inaudible] the whole industry. Starting from the company, there are social media platforms. Wherever a person is talking about that particular thing, I try to collect the data. And this has datasets of zero search volumes. I don’t care about volume. I care about, is there one user that is going to buy my product? I'm going to answer them. So I built the whole cluster. For the next, probably one or two years, I created a self-learning mechanism where it will automatically schedule the crawls, collect the data, and update itself."
      }
    ]
  },
  {
    "at": 731,
    "title": "Market share",
    "paragraphs": [
      {
        "at": 731,
        "speaker": "venkata",
        "text": "Okay, then you go to \"person who writes checks\". [inaudible] “Okay man, you have 5.6 million queries. Why should I write a check for you?” Easy hack is: do you want to do market share for your company? The one question that you write a check for. Hey, do you want to invest double money to recover? Or do you want to invest money? Be ahead of them. Okay, this is one of my favorite slides in the whole thing."
      }
    ]
  },
  {
    "at": 761,
    "title": "Reviews into products",
    "paragraphs": [
      {
        "at": 761,
        "speaker": "venkata",
        "text": "I was curious and this research is not funded by any organization except myself. I was analyzing 100,000 reviews on all the local telecom stores in Texas. What I find, I don't know yet, but what I found was amazing. So the second pain point was, I'm sorry, long wait time. The pain point of the users when they walk into the stores is that they hate waiting. None of the traditional tools tell a problem or pain points, but analyzing and classifying data tells that."
      },
      {
        "at": 796,
        "speaker": "venkata",
        "text": "So, long wait time. What I have to do with the long wait time? You can build a product such as digital check-ins, or you can build an in-app virtual appointments. That can bring revenue, reduce pain points, and help [inaudible] as well. So that's the beauty of you, collecting the data from different sources, you classifying them and building the products based on pain points. So, it's good, I did it all myself, and I have a great mentor who I work with. His name is Gene. He challenges me every time."
      }
    ]
  },
  {
    "at": 827,
    "title": "Agent systems",
    "paragraphs": [
      {
        "at": 834,
        "speaker": "venkata",
        "text": "Okay, this is great. How can this be used by 10,000 people at the same time? So I created a multi-level AI agent orchestration, where agents can talk to each other. Is it great? No, I'm still learning and fixing it, but I was able to build a great agents that can 60 to 70% do my job, and then I can verify that. So, I'm not going to talk about all these things because I want to use [inaudible] for the most important person in my life."
      }
    ]
  },
  {
    "at": 866,
    "title": "Dedication",
    "paragraphs": [
      {
        "at": 867,
        "speaker": "venkata",
        "text": "It's my mom. So, she's the first person to believe in me. I came from India, a whole different country, did my masters. And I'm here, this is like a dream for me. But one person trusted me when I was zero, is my mom. is my mom. So, I would like to take this platform and give it to my mom. [inaudible] So, that's it. [Applause]"
      }
    ]
  }
];
