/**
 * What the pages currently ranking for these questions actually claim,
 * and what each of them measured.
 *
 * Generated by data/corpus/gen_claims_ts.py. Captured from live SERPs,
 * stored in research_corpus, never hand-typed.
 *
 * The basis field is the whole point. "Snapchat is 38% 18-24" and
 * "Snapchat is 90% 13-24" are not competing estimates of one number:
 * one counts ad-platform reach globally, the other counts it in
 * selected markets, and neither counts people. Published side by side
 * with what they measured, the disagreement explains itself.
 */

export type ClaimBasis = "ad_audience" | "survey" | "vendor_panel" | "unstated";

export const BASIS_META: Record<ClaimBasis, { label: string; what: string; color: string }> = {
  survey: {
    label: "Probability sample",
    what: "A random sample of people, with a published sample size and margin of error. The only basis that supports a claim about a population.",
    color: "#10b981",
  },
  vendor_panel: {
    label: "Opt-in panel",
    what: "People who signed up to be surveyed. Useful, but panel members are not a random sample of the country and the tool rarely says how many answered.",
    color: "#3b82f6",
  },
  ad_audience: {
    label: "Ad-platform reach",
    what: "The number the advertising tool shows when you build an audience. It counts reachable accounts, not people: one person with two accounts counts twice, and a bot counts once.",
    color: "#f59e0b",
  },
  unstated: {
    label: "No basis given",
    what: "A percentage with no sample, no method and no source you can open. Most commonly a figure copied from another page that copied it.",
    color: "#ef4444",
  },
};

export interface CompetitorClaim {
  subject: string;
  domain: string;
  url: string;
  claim: string;
  value: string;
  basis: ClaimBasis;
  population: string;
  citedSource: string;
  keyword: string;
}

export const COMPETITOR_CLAIMS: CompetitorClaim[] = [
  {"subject": "snapchat", "domain": "google-ai-overview", "url": "https://www.google.com/search?q=who+uses+snapchat+demographics", "claim": "13-17 year olds are 18-20% of users; 18-24 are 35-38%", "value": "35-38%", "basis": "ad_audience", "population": "global", "citedSource": "aggregated from the above", "keyword": "who uses snapchat demographics"},
  {"subject": "snapchat", "domain": "increv.co", "url": "https://increv.co/academy/snapchat-users/", "claim": "38.1% of ad audience is 18-24", "value": "38.1%", "basis": "ad_audience", "population": "global", "citedSource": "Snap ad platform", "keyword": "who uses snapchat demographics"},
  {"subject": "snapchat", "domain": "sproutsocial.com", "url": "https://sproutsocial.com/insights/snapchat-statistics/", "claim": "Audience nearly evenly split male 50.7% / female 48.4%", "value": "50.7% male", "basis": "ad_audience", "population": "global", "citedSource": "Snap ad platform", "keyword": "who uses snapchat demographics"},
  {"subject": "snapchat", "domain": "www.charleagency.com", "url": "https://www.charleagency.com/articles/snapchat-statistics/", "claim": "90% of 13-24 year olds use Snapchat in key markets", "value": "90%", "basis": "ad_audience", "population": "global", "citedSource": "Snap ad platform", "keyword": "who uses snapchat demographics"},
  {"subject": "snapchat", "domain": "thesocialshepherd.com", "url": "https://thesocialshepherd.com/blog/snapchat-statistics", "claim": "Ages 15-25 are 48% of US users", "value": "48%", "basis": "unstated", "population": "us", "citedSource": "", "keyword": "who uses snapchat demographics"},
  {"subject": "snapchat", "domain": "www.demandsage.com", "url": "https://www.demandsage.com/snapchat-users/", "claim": "48% of US users are 15-25", "value": "48%", "basis": "unstated", "population": "us", "citedSource": "", "keyword": "who uses snapchat demographics"},
  {"subject": "snapchat", "domain": "www.statista.com", "url": "https://www.statista.com/statistics/545967/snapchat-app-dau/", "claim": "48% of US internet users aged 15-25 use Snapchat", "value": "48%", "basis": "vendor_panel", "population": "us", "citedSource": "Statista Consumer Insights", "keyword": "who uses snapchat demographics"},
];

export interface SerpRow { keyword: string; rank: number; type: string; domain: string; title: string; citedByAi: boolean; }

export const SERP_ROWS: SerpRow[] = [
  {"keyword": "who uses snapchat demographics", "rank": 2, "type": "organic", "domain": "sproutsocial.com", "title": "Snapchat statistics, revenue and usage data for 2026", "citedByAi": true},
  {"keyword": "who uses snapchat demographics", "rank": 4, "type": "organic", "domain": "thesocialshepherd.com", "title": "25 Essential Snapchat Statistics You Need to Know in 2026", "citedByAi": false},
  {"keyword": "who uses snapchat demographics", "rank": 5, "type": "organic", "domain": "www.reddit.com", "title": "Snapchat hasn't grown in North America for years", "citedByAi": false},
  {"keyword": "who uses snapchat demographics", "rank": 6, "type": "organic", "domain": "increv.co", "title": "Snapchat Demographic Stats", "citedByAi": true},
  {"keyword": "who uses snapchat demographics", "rank": 7, "type": "organic", "domain": "www.charleagency.com", "title": "70+ Snapchat Statistics for 2026", "citedByAi": true},
  {"keyword": "who uses snapchat demographics", "rank": 8, "type": "organic", "domain": "www.demandsage.com", "title": "How Many People Use Snapchat in 2026", "citedByAi": false},
  {"keyword": "who uses snapchat demographics", "rank": 9, "type": "organic", "domain": "thunderbit.com", "title": "100 Latest Snapchat Usage Statistics", "citedByAi": true},
  {"keyword": "who uses snapchat demographics", "rank": 10, "type": "organic", "domain": "www.statista.com", "title": "Daily active users of Snapchat 2014-2026", "citedByAi": true},
  {"keyword": "who uses snapchat demographics", "rank": 11, "type": "organic", "domain": "newsroom.snap.com", "title": "The Snapchat Generation Report", "citedByAi": false},
  {"keyword": "who uses snapchat demographics", "rank": 90, "type": "ai_overview", "domain": "www.podbase.com", "title": "cited by AI Overview only", "citedByAi": true},
  {"keyword": "who uses snapchat demographics", "rank": 91, "type": "ai_overview", "domain": "www.medianug.com", "title": "cited by AI Overview only", "citedByAi": true},
  {"keyword": "who uses snapchat demographics", "rank": 92, "type": "ai_overview", "domain": "www.themedialab.me", "title": "cited by AI Overview only", "citedByAi": true},
  {"keyword": "who uses snapchat demographics", "rank": 93, "type": "ai_overview", "domain": "www.youtube.com", "title": "cited by AI Overview only", "citedByAi": true},
];

export const claimsFor = (subject: string) =>
  COMPETITOR_CLAIMS.filter((c) => c.subject === subject);
