/**
 * Generated by scripts/gen-paper-covers.py. Do not edit by hand.
 *
 * Width and height come from the rendered file itself, so the browser can
 * reserve the exact box before the image arrives and the paper rows do not
 * jump as they load. Page sizes differ between publishers (A4 and US Letter),
 * which is why these are measured per paper rather than assumed.
 */
export interface PaperCover {
  src: string;
  width: number;
  height: number;
}

export const PAPER_COVERS: Record<string, PaperCover> = {
  "llms-disrupting-search": { src: "/research/papers/llms-disrupting-search.jpg", width: 620, height: 803 },
  "reward-hacking-agentic-llms": { src: "/research/papers/reward-hacking-agentic-llms.jpg", width: 620, height: 827 },
  "ai-helpful-content-ecommerce": { src: "/research/papers/ai-helpful-content-ecommerce.jpg", width: 620, height: 798 },
};
